/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SanctioningRouteImport } from './routes/sanctioning'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as LogOutRouteImport } from './routes/log-out'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as JuniorsRouteImport } from './routes/juniors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as VenuesVenueIdRouteImport } from './routes/venues/$venueId'
import { Route as TournamentsCreateRouteImport } from './routes/tournaments/create'
import { Route as ProfileProfileIdRouteImport } from './routes/profile/$profileId'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as AccountSetupRouteImport } from './routes/account/setup'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments/$tournamentId/index'
import { Route as AccountVerifyIndexRouteImport } from './routes/account/verify/index'
import { Route as TournamentsTournamentIdDivisionIdRouteImport } from './routes/tournaments/$tournamentId/$divisionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AccountVerifySuccessRouteImport } from './routes/account/verify/success'
import { Route as MatchesPoolMatchIdIndexRouteImport } from './routes/matches/pool/$matchId/index'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctioningRoute = SanctioningRouteImport.update({
  id: '/sanctioning',
  path: '/sanctioning',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogOutRoute = LogOutRouteImport.update({
  id: '/log-out',
  path: '/log-out',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorsRoute = JuniorsRouteImport.update({
  id: '/juniors',
  path: '/juniors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsCreateRoute = TournamentsCreateRouteImport.update({
  id: '/tournaments/create',
  path: '/tournaments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdRoute = ProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: '/account/setup',
  path: '/account/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/tournaments/$tournamentId/',
    path: '/tournaments/$tournamentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountVerifyIndexRoute = AccountVerifyIndexRouteImport.update({
  id: '/account/verify/',
  path: '/account/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdDivisionIdRoute =
  TournamentsTournamentIdDivisionIdRouteImport.update({
    id: '/tournaments/$tournamentId/$divisionId',
    path: '/tournaments/$tournamentId/$divisionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifySuccessRoute = AccountVerifySuccessRouteImport.update({
  id: '/account/verify/success',
  path: '/account/verify/success',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesPoolMatchIdIndexRoute = MatchesPoolMatchIdIndexRouteImport.update({
  id: '/matches/pool/$matchId/',
  path: '/matches/pool/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/juniors': typeof JuniorsRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/setup': typeof AccountSetupRoute
  '/api/files': typeof ApiFilesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account': typeof AccountIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tournaments/$tournamentId/$divisionId': typeof TournamentsTournamentIdDivisionIdRoute
  '/account/verify': typeof AccountVerifyIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/matches/pool/$matchId': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/juniors': typeof JuniorsRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/setup': typeof AccountSetupRoute
  '/api/files': typeof ApiFilesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account': typeof AccountIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tournaments/$tournamentId/$divisionId': typeof TournamentsTournamentIdDivisionIdRoute
  '/account/verify': typeof AccountVerifyIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/matches/pool/$matchId': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/juniors': typeof JuniorsRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/setup': typeof AccountSetupRoute
  '/api/files': typeof ApiFilesRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account/': typeof AccountIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tournaments/$tournamentId/$divisionId': typeof TournamentsTournamentIdDivisionIdRoute
  '/account/verify/': typeof AccountVerifyIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/matches/pool/$matchId/': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/juniors'
    | '/log-in'
    | '/log-out'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/setup'
    | '/api/files'
    | '/profile/$profileId'
    | '/tournaments/create'
    | '/venues/$venueId'
    | '/account'
    | '/tournaments'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/tournaments/$tournamentId/$divisionId'
    | '/account/verify'
    | '/tournaments/$tournamentId'
    | '/matches/pool/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/juniors'
    | '/log-in'
    | '/log-out'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/setup'
    | '/api/files'
    | '/profile/$profileId'
    | '/tournaments/create'
    | '/venues/$venueId'
    | '/account'
    | '/tournaments'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/tournaments/$tournamentId/$divisionId'
    | '/account/verify'
    | '/tournaments/$tournamentId'
    | '/matches/pool/$matchId'
  id:
    | '__root__'
    | '/'
    | '/juniors'
    | '/log-in'
    | '/log-out'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/setup'
    | '/api/files'
    | '/profile/$profileId'
    | '/tournaments/create'
    | '/venues/$venueId'
    | '/account/'
    | '/tournaments/'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/tournaments/$tournamentId/$divisionId'
    | '/account/verify/'
    | '/tournaments/$tournamentId/'
    | '/matches/pool/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JuniorsRoute: typeof JuniorsRoute
  LogInRoute: typeof LogInRoute
  LogOutRoute: typeof LogOutRoute
  RatingsRoute: typeof RatingsRoute
  SanctioningRoute: typeof SanctioningRoute
  SearchRoute: typeof SearchRoute
  SignUpRoute: typeof SignUpRoute
  AccountSetupRoute: typeof AccountSetupRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ProfileProfileIdRoute: typeof ProfileProfileIdRoute
  TournamentsCreateRoute: typeof TournamentsCreateRoute
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  AccountVerifySuccessRoute: typeof AccountVerifySuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TournamentsTournamentIdDivisionIdRoute: typeof TournamentsTournamentIdDivisionIdRoute
  AccountVerifyIndexRoute: typeof AccountVerifyIndexRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
  MatchesPoolMatchIdIndexRoute: typeof MatchesPoolMatchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctioning': {
      id: '/sanctioning'
      path: '/sanctioning'
      fullPath: '/sanctioning'
      preLoaderRoute: typeof SanctioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-out': {
      id: '/log-out'
      path: '/log-out'
      fullPath: '/log-out'
      preLoaderRoute: typeof LogOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juniors': {
      id: '/juniors'
      path: '/juniors'
      fullPath: '/juniors'
      preLoaderRoute: typeof JuniorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId': {
      id: '/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/create': {
      id: '/tournaments/create'
      path: '/tournaments/create'
      fullPath: '/tournaments/create'
      preLoaderRoute: typeof TournamentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId': {
      id: '/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/setup': {
      id: '/account/setup'
      path: '/account/setup'
      fullPath: '/account/setup'
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify/': {
      id: '/account/verify/'
      path: '/account/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AccountVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/$divisionId': {
      id: '/tournaments/$tournamentId/$divisionId'
      path: '/tournaments/$tournamentId/$divisionId'
      fullPath: '/tournaments/$tournamentId/$divisionId'
      preLoaderRoute: typeof TournamentsTournamentIdDivisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify/success': {
      id: '/account/verify/success'
      path: '/account/verify/success'
      fullPath: '/account/verify/success'
      preLoaderRoute: typeof AccountVerifySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/pool/$matchId/': {
      id: '/matches/pool/$matchId/'
      path: '/matches/pool/$matchId'
      fullPath: '/matches/pool/$matchId'
      preLoaderRoute: typeof MatchesPoolMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JuniorsRoute: JuniorsRoute,
  LogInRoute: LogInRoute,
  LogOutRoute: LogOutRoute,
  RatingsRoute: RatingsRoute,
  SanctioningRoute: SanctioningRoute,
  SearchRoute: SearchRoute,
  SignUpRoute: SignUpRoute,
  AccountSetupRoute: AccountSetupRoute,
  ApiFilesRoute: ApiFilesRoute,
  ProfileProfileIdRoute: ProfileProfileIdRoute,
  TournamentsCreateRoute: TournamentsCreateRoute,
  VenuesVenueIdRoute: VenuesVenueIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  AccountVerifySuccessRoute: AccountVerifySuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TournamentsTournamentIdDivisionIdRoute:
    TournamentsTournamentIdDivisionIdRoute,
  AccountVerifyIndexRoute: AccountVerifyIndexRoute,
  TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
  MatchesPoolMatchIdIndexRoute: MatchesPoolMatchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
