/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SanctioningRouteImport } from './routes/sanctioning'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LogOutRouteImport } from './routes/log-out'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as JuniorsIndexRouteImport } from './routes/juniors/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as VenuesVenueIdRouteImport } from './routes/venues/$venueId'
import { Route as TournamentsCreateRouteImport } from './routes/tournaments/create'
import { Route as ProfileProfileIdRouteImport } from './routes/profile/$profileId'
import { Route as JuniorsLeaderboardRouteImport } from './routes/juniors/leaderboard'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AccountSetupRouteImport } from './routes/account/setup'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments/$tournamentId/index'
import { Route as AccountVerifyIndexRouteImport } from './routes/account/verify/index'
import { Route as ProfileProfileIdEditRouteImport } from './routes/profile/$profileId.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AccountVerifySuccessRouteImport } from './routes/account/verify/success'
import { Route as MatchesPoolMatchIdIndexRouteImport } from './routes/matches/pool/$matchId/index'
import { Route as TournamentsTournamentIdDivisionIdChar123TabChar125RouteImport } from './routes/tournaments/$tournamentId/$divisionId.{-$tab}'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctioningRoute = SanctioningRouteImport.update({
  id: '/sanctioning',
  path: '/sanctioning',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LogOutRoute = LogOutRouteImport.update({
  id: '/log-out',
  path: '/log-out',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorsIndexRoute = JuniorsIndexRouteImport.update({
  id: '/juniors/',
  path: '/juniors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsCreateRoute = TournamentsCreateRouteImport.update({
  id: '/tournaments/create',
  path: '/tournaments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdRoute = ProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorsLeaderboardRoute = JuniorsLeaderboardRouteImport.update({
  id: '/juniors/leaderboard',
  path: '/juniors/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: '/account/setup',
  path: '/account/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/tournaments/$tournamentId/',
    path: '/tournaments/$tournamentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountVerifyIndexRoute = AccountVerifyIndexRouteImport.update({
  id: '/account/verify/',
  path: '/account/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdEditRoute = ProfileProfileIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileProfileIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifySuccessRoute = AccountVerifySuccessRouteImport.update({
  id: '/account/verify/success',
  path: '/account/verify/success',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesPoolMatchIdIndexRoute = MatchesPoolMatchIdIndexRouteImport.update({
  id: '/matches/pool/$matchId/',
  path: '/matches/pool/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdDivisionIdChar123TabChar125Route =
  TournamentsTournamentIdDivisionIdChar123TabChar125RouteImport.update({
    id: '/tournaments/$tournamentId/$divisionId/{-$tab}',
    path: '/tournaments/$tournamentId/$divisionId/{-$tab}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/not-found': typeof NotFoundRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/files': typeof ApiFilesRoute
  '/juniors/leaderboard': typeof JuniorsLeaderboardRoute
  '/profile/$profileId': typeof ProfileProfileIdRouteWithChildren
  '/tournaments/create': typeof TournamentsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/juniors': typeof JuniorsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
  '/account/verify': typeof AccountVerifyIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/$divisionId/{-$tab}': typeof TournamentsTournamentIdDivisionIdChar123TabChar125Route
  '/matches/pool/$matchId': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/not-found': typeof NotFoundRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/files': typeof ApiFilesRoute
  '/juniors/leaderboard': typeof JuniorsLeaderboardRoute
  '/profile/$profileId': typeof ProfileProfileIdRouteWithChildren
  '/tournaments/create': typeof TournamentsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/juniors': typeof JuniorsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
  '/account/verify': typeof AccountVerifyIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/$divisionId/{-$tab}': typeof TournamentsTournamentIdDivisionIdChar123TabChar125Route
  '/matches/pool/$matchId': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/not-found': typeof NotFoundRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/files': typeof ApiFilesRoute
  '/juniors/leaderboard': typeof JuniorsLeaderboardRoute
  '/profile/$profileId': typeof ProfileProfileIdRouteWithChildren
  '/tournaments/create': typeof TournamentsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/juniors/': typeof JuniorsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
  '/account/verify/': typeof AccountVerifyIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/$divisionId/{-$tab}': typeof TournamentsTournamentIdDivisionIdChar123TabChar125Route
  '/matches/pool/$matchId/': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/leaderboard'
    | '/log-in'
    | '/log-out'
    | '/not-found'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/forgot-password'
    | '/account/reset-password'
    | '/account/setup'
    | '/admin/schedule'
    | '/admin/users'
    | '/api/files'
    | '/juniors/leaderboard'
    | '/profile/$profileId'
    | '/tournaments/create'
    | '/venues/$venueId'
    | '/account'
    | '/admin'
    | '/juniors'
    | '/tournaments'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/profile/$profileId/edit'
    | '/account/verify'
    | '/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/$divisionId/{-$tab}'
    | '/matches/pool/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/leaderboard'
    | '/log-in'
    | '/log-out'
    | '/not-found'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/forgot-password'
    | '/account/reset-password'
    | '/account/setup'
    | '/admin/schedule'
    | '/admin/users'
    | '/api/files'
    | '/juniors/leaderboard'
    | '/profile/$profileId'
    | '/tournaments/create'
    | '/venues/$venueId'
    | '/account'
    | '/admin'
    | '/juniors'
    | '/tournaments'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/profile/$profileId/edit'
    | '/account/verify'
    | '/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/$divisionId/{-$tab}'
    | '/matches/pool/$matchId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/leaderboard'
    | '/log-in'
    | '/log-out'
    | '/not-found'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/forgot-password'
    | '/account/reset-password'
    | '/account/setup'
    | '/admin/schedule'
    | '/admin/users'
    | '/api/files'
    | '/juniors/leaderboard'
    | '/profile/$profileId'
    | '/tournaments/create'
    | '/venues/$venueId'
    | '/account/'
    | '/admin/'
    | '/juniors/'
    | '/tournaments/'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/profile/$profileId/edit'
    | '/account/verify/'
    | '/tournaments/$tournamentId/'
    | '/tournaments/$tournamentId/$divisionId/{-$tab}'
    | '/matches/pool/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LogInRoute: typeof LogInRoute
  LogOutRoute: typeof LogOutRoute
  NotFoundRoute: typeof NotFoundRoute
  RatingsRoute: typeof RatingsRoute
  SanctioningRoute: typeof SanctioningRoute
  SearchRoute: typeof SearchRoute
  SignUpRoute: typeof SignUpRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSetupRoute: typeof AccountSetupRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiFilesRoute: typeof ApiFilesRoute
  JuniorsLeaderboardRoute: typeof JuniorsLeaderboardRoute
  ProfileProfileIdRoute: typeof ProfileProfileIdRouteWithChildren
  TournamentsCreateRoute: typeof TournamentsCreateRoute
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JuniorsIndexRoute: typeof JuniorsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  AccountVerifySuccessRoute: typeof AccountVerifySuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AccountVerifyIndexRoute: typeof AccountVerifyIndexRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
  TournamentsTournamentIdDivisionIdChar123TabChar125Route: typeof TournamentsTournamentIdDivisionIdChar123TabChar125Route
  MatchesPoolMatchIdIndexRoute: typeof MatchesPoolMatchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctioning': {
      id: '/sanctioning'
      path: '/sanctioning'
      fullPath: '/sanctioning'
      preLoaderRoute: typeof SanctioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-out': {
      id: '/log-out'
      path: '/log-out'
      fullPath: '/log-out'
      preLoaderRoute: typeof LogOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juniors/': {
      id: '/juniors/'
      path: '/juniors'
      fullPath: '/juniors'
      preLoaderRoute: typeof JuniorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId': {
      id: '/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/create': {
      id: '/tournaments/create'
      path: '/tournaments/create'
      fullPath: '/tournaments/create'
      preLoaderRoute: typeof TournamentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId': {
      id: '/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juniors/leaderboard': {
      id: '/juniors/leaderboard'
      path: '/juniors/leaderboard'
      fullPath: '/juniors/leaderboard'
      preLoaderRoute: typeof JuniorsLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/setup': {
      id: '/account/setup'
      path: '/account/setup'
      fullPath: '/account/setup'
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify/': {
      id: '/account/verify/'
      path: '/account/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AccountVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId/edit': {
      id: '/profile/$profileId/edit'
      path: '/edit'
      fullPath: '/profile/$profileId/edit'
      preLoaderRoute: typeof ProfileProfileIdEditRouteImport
      parentRoute: typeof ProfileProfileIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify/success': {
      id: '/account/verify/success'
      path: '/account/verify/success'
      fullPath: '/account/verify/success'
      preLoaderRoute: typeof AccountVerifySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/pool/$matchId/': {
      id: '/matches/pool/$matchId/'
      path: '/matches/pool/$matchId'
      fullPath: '/matches/pool/$matchId'
      preLoaderRoute: typeof MatchesPoolMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/$divisionId/{-$tab}': {
      id: '/tournaments/$tournamentId/$divisionId/{-$tab}'
      path: '/tournaments/$tournamentId/$divisionId/{-$tab}'
      fullPath: '/tournaments/$tournamentId/$divisionId/{-$tab}'
      preLoaderRoute: typeof TournamentsTournamentIdDivisionIdChar123TabChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileProfileIdRouteChildren {
  ProfileProfileIdEditRoute: typeof ProfileProfileIdEditRoute
}

const ProfileProfileIdRouteChildren: ProfileProfileIdRouteChildren = {
  ProfileProfileIdEditRoute: ProfileProfileIdEditRoute,
}

const ProfileProfileIdRouteWithChildren =
  ProfileProfileIdRoute._addFileChildren(ProfileProfileIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LeaderboardRoute: LeaderboardRoute,
  LogInRoute: LogInRoute,
  LogOutRoute: LogOutRoute,
  NotFoundRoute: NotFoundRoute,
  RatingsRoute: RatingsRoute,
  SanctioningRoute: SanctioningRoute,
  SearchRoute: SearchRoute,
  SignUpRoute: SignUpRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSetupRoute: AccountSetupRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiFilesRoute: ApiFilesRoute,
  JuniorsLeaderboardRoute: JuniorsLeaderboardRoute,
  ProfileProfileIdRoute: ProfileProfileIdRouteWithChildren,
  TournamentsCreateRoute: TournamentsCreateRoute,
  VenuesVenueIdRoute: VenuesVenueIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  JuniorsIndexRoute: JuniorsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  AccountVerifySuccessRoute: AccountVerifySuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AccountVerifyIndexRoute: AccountVerifyIndexRoute,
  TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
  TournamentsTournamentIdDivisionIdChar123TabChar125Route:
    TournamentsTournamentIdDivisionIdChar123TabChar125Route,
  MatchesPoolMatchIdIndexRoute: MatchesPoolMatchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
