/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SanctioningRouteImport } from './routes/sanctioning'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LogOutRouteImport } from './routes/log-out'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TdIndexRouteImport } from './routes/td/index'
import { Route as JuniorsIndexRouteImport } from './routes/juniors/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as VenuesVenueIdRouteImport } from './routes/venues/$venueId'
import { Route as TournamentsFaqsRouteImport } from './routes/tournaments/faqs'
import { Route as TournamentsCreateRouteImport } from './routes/tournaments/create'
import { Route as LeaderboardChar123GenderChar125RouteImport } from './routes/leaderboard.{-$gender}'
import { Route as JuniorsCalCupRouteImport } from './routes/juniors/cal-cup'
import { Route as InfoCedarsRouteImport } from './routes/info/cedars'
import { Route as FaqsChar123SubjectChar125RouteImport } from './routes/faqs.{-$subject}'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminInvoicesRouteImport } from './routes/admin/invoices'
import { Route as AccountSetupRouteImport } from './routes/account/setup'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AccountChangePasswordRouteImport } from './routes/account/change-password'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments/$tournamentId/index'
import { Route as ProfileProfileIdIndexRouteImport } from './routes/profile/$profileId/index'
import { Route as AccountVerifyIndexRouteImport } from './routes/account/verify/index'
import { Route as AccountRegistrationsIndexRouteImport } from './routes/account/registrations/index'
import { Route as TournamentsTournamentIdEditRouteImport } from './routes/tournaments/$tournamentId/edit'
import { Route as ProfileProfileIdEditRouteImport } from './routes/profile/$profileId/edit'
import { Route as JuniorsLeaderboardChar123GenderChar125RouteImport } from './routes/juniors/leaderboard.{-$gender}'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AccountVerifySuccessRouteImport } from './routes/account/verify/success'
import { Route as AccountRegistrationsCheckoutRouteImport } from './routes/account/registrations/checkout'
import { Route as MatchesPoolMatchIdIndexRouteImport } from './routes/matches/pool/$matchId/index'
import { Route as MatchesPlayoffMatchIdIndexRouteImport } from './routes/matches/playoff/$matchId/index'
import { Route as TournamentsTournamentIdDivisionIdChar123TabChar125RouteImport } from './routes/tournaments/$tournamentId/$divisionId.{-$tab}'
import { Route as ApiTasksCleanupStorageRouteImport } from './routes/api/tasks/cleanup/storage'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctioningRoute = SanctioningRouteImport.update({
  id: '/sanctioning',
  path: '/sanctioning',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LogOutRoute = LogOutRouteImport.update({
  id: '/log-out',
  path: '/log-out',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TdIndexRoute = TdIndexRouteImport.update({
  id: '/td/',
  path: '/td/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorsIndexRoute = JuniorsIndexRouteImport.update({
  id: '/juniors/',
  path: '/juniors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsFaqsRoute = TournamentsFaqsRouteImport.update({
  id: '/tournaments/faqs',
  path: '/tournaments/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsCreateRoute = TournamentsCreateRouteImport.update({
  id: '/tournaments/create',
  path: '/tournaments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardChar123GenderChar125Route =
  LeaderboardChar123GenderChar125RouteImport.update({
    id: '/leaderboard/{-$gender}',
    path: '/leaderboard/{-$gender}',
    getParentRoute: () => rootRouteImport,
  } as any)
const JuniorsCalCupRoute = JuniorsCalCupRouteImport.update({
  id: '/juniors/cal-cup',
  path: '/juniors/cal-cup',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoCedarsRoute = InfoCedarsRouteImport.update({
  id: '/info/cedars',
  path: '/info/cedars',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsChar123SubjectChar125Route =
  FaqsChar123SubjectChar125RouteImport.update({
    id: '/faqs/{-$subject}',
    path: '/faqs/{-$subject}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: '/account/setup',
  path: '/account/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountChangePasswordRoute = AccountChangePasswordRouteImport.update({
  id: '/account/change-password',
  path: '/account/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/tournaments/$tournamentId/',
    path: '/tournaments/$tournamentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileProfileIdIndexRoute = ProfileProfileIdIndexRouteImport.update({
  id: '/profile/$profileId/',
  path: '/profile/$profileId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyIndexRoute = AccountVerifyIndexRouteImport.update({
  id: '/account/verify/',
  path: '/account/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegistrationsIndexRoute =
  AccountRegistrationsIndexRouteImport.update({
    id: '/account/registrations/',
    path: '/account/registrations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdEditRoute =
  TournamentsTournamentIdEditRouteImport.update({
    id: '/tournaments/$tournamentId/edit',
    path: '/tournaments/$tournamentId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileProfileIdEditRoute = ProfileProfileIdEditRouteImport.update({
  id: '/profile/$profileId/edit',
  path: '/profile/$profileId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorsLeaderboardChar123GenderChar125Route =
  JuniorsLeaderboardChar123GenderChar125RouteImport.update({
    id: '/juniors/leaderboard/{-$gender}',
    path: '/juniors/leaderboard/{-$gender}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifySuccessRoute = AccountVerifySuccessRouteImport.update({
  id: '/account/verify/success',
  path: '/account/verify/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegistrationsCheckoutRoute =
  AccountRegistrationsCheckoutRouteImport.update({
    id: '/account/registrations/checkout',
    path: '/account/registrations/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const MatchesPoolMatchIdIndexRoute = MatchesPoolMatchIdIndexRouteImport.update({
  id: '/matches/pool/$matchId/',
  path: '/matches/pool/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesPlayoffMatchIdIndexRoute =
  MatchesPlayoffMatchIdIndexRouteImport.update({
    id: '/matches/playoff/$matchId/',
    path: '/matches/playoff/$matchId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdDivisionIdChar123TabChar125Route =
  TournamentsTournamentIdDivisionIdChar123TabChar125RouteImport.update({
    id: '/tournaments/$tournamentId/$divisionId/{-$tab}',
    path: '/tournaments/$tournamentId/$divisionId/{-$tab}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTasksCleanupStorageRoute = ApiTasksCleanupStorageRouteImport.update({
  id: '/api/tasks/cleanup/storage',
  path: '/api/tasks/cleanup/storage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/not-found': typeof NotFoundRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/faqs/{-$subject}': typeof FaqsChar123SubjectChar125Route
  '/info/cedars': typeof InfoCedarsRoute
  '/juniors/cal-cup': typeof JuniorsCalCupRoute
  '/leaderboard/{-$gender}': typeof LeaderboardChar123GenderChar125Route
  '/tournaments/create': typeof TournamentsCreateRoute
  '/tournaments/faqs': typeof TournamentsFaqsRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/juniors': typeof JuniorsIndexRoute
  '/td': typeof TdIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/account/registrations/checkout': typeof AccountRegistrationsCheckoutRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/juniors/leaderboard/{-$gender}': typeof JuniorsLeaderboardChar123GenderChar125Route
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/account/registrations': typeof AccountRegistrationsIndexRoute
  '/account/verify': typeof AccountVerifyIndexRoute
  '/profile/$profileId': typeof ProfileProfileIdIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/api/tasks/cleanup/storage': typeof ApiTasksCleanupStorageRoute
  '/tournaments/$tournamentId/$divisionId/{-$tab}': typeof TournamentsTournamentIdDivisionIdChar123TabChar125Route
  '/matches/playoff/$matchId': typeof MatchesPlayoffMatchIdIndexRoute
  '/matches/pool/$matchId': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/not-found': typeof NotFoundRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/faqs/{-$subject}': typeof FaqsChar123SubjectChar125Route
  '/info/cedars': typeof InfoCedarsRoute
  '/juniors/cal-cup': typeof JuniorsCalCupRoute
  '/leaderboard/{-$gender}': typeof LeaderboardChar123GenderChar125Route
  '/tournaments/create': typeof TournamentsCreateRoute
  '/tournaments/faqs': typeof TournamentsFaqsRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/juniors': typeof JuniorsIndexRoute
  '/td': typeof TdIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/account/registrations/checkout': typeof AccountRegistrationsCheckoutRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/juniors/leaderboard/{-$gender}': typeof JuniorsLeaderboardChar123GenderChar125Route
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/account/registrations': typeof AccountRegistrationsIndexRoute
  '/account/verify': typeof AccountVerifyIndexRoute
  '/profile/$profileId': typeof ProfileProfileIdIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/api/tasks/cleanup/storage': typeof ApiTasksCleanupStorageRoute
  '/tournaments/$tournamentId/$divisionId/{-$tab}': typeof TournamentsTournamentIdDivisionIdChar123TabChar125Route
  '/matches/playoff/$matchId': typeof MatchesPlayoffMatchIdIndexRoute
  '/matches/pool/$matchId': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/log-in': typeof LogInRoute
  '/log-out': typeof LogOutRoute
  '/not-found': typeof NotFoundRoute
  '/ratings': typeof RatingsRoute
  '/sanctioning': typeof SanctioningRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/faqs/{-$subject}': typeof FaqsChar123SubjectChar125Route
  '/info/cedars': typeof InfoCedarsRoute
  '/juniors/cal-cup': typeof JuniorsCalCupRoute
  '/leaderboard/{-$gender}': typeof LeaderboardChar123GenderChar125Route
  '/tournaments/create': typeof TournamentsCreateRoute
  '/tournaments/faqs': typeof TournamentsFaqsRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/juniors/': typeof JuniorsIndexRoute
  '/td/': typeof TdIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/account/registrations/checkout': typeof AccountRegistrationsCheckoutRoute
  '/account/verify/success': typeof AccountVerifySuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/juniors/leaderboard/{-$gender}': typeof JuniorsLeaderboardChar123GenderChar125Route
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/account/registrations/': typeof AccountRegistrationsIndexRoute
  '/account/verify/': typeof AccountVerifyIndexRoute
  '/profile/$profileId/': typeof ProfileProfileIdIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/api/tasks/cleanup/storage': typeof ApiTasksCleanupStorageRoute
  '/tournaments/$tournamentId/$divisionId/{-$tab}': typeof TournamentsTournamentIdDivisionIdChar123TabChar125Route
  '/matches/playoff/$matchId/': typeof MatchesPlayoffMatchIdIndexRoute
  '/matches/pool/$matchId/': typeof MatchesPoolMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/log-in'
    | '/log-out'
    | '/not-found'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/change-password'
    | '/account/forgot-password'
    | '/account/reset-password'
    | '/account/setup'
    | '/admin/invoices'
    | '/admin/schedule'
    | '/admin/users'
    | '/api/ping'
    | '/faqs/{-$subject}'
    | '/info/cedars'
    | '/juniors/cal-cup'
    | '/leaderboard/{-$gender}'
    | '/tournaments/create'
    | '/tournaments/faqs'
    | '/venues/$venueId'
    | '/account'
    | '/admin'
    | '/juniors'
    | '/td'
    | '/tournaments'
    | '/account/registrations/checkout'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/juniors/leaderboard/{-$gender}'
    | '/profile/$profileId/edit'
    | '/tournaments/$tournamentId/edit'
    | '/account/registrations'
    | '/account/verify'
    | '/profile/$profileId'
    | '/tournaments/$tournamentId'
    | '/api/tasks/cleanup/storage'
    | '/tournaments/$tournamentId/$divisionId/{-$tab}'
    | '/matches/playoff/$matchId'
    | '/matches/pool/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/log-in'
    | '/log-out'
    | '/not-found'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/change-password'
    | '/account/forgot-password'
    | '/account/reset-password'
    | '/account/setup'
    | '/admin/invoices'
    | '/admin/schedule'
    | '/admin/users'
    | '/api/ping'
    | '/faqs/{-$subject}'
    | '/info/cedars'
    | '/juniors/cal-cup'
    | '/leaderboard/{-$gender}'
    | '/tournaments/create'
    | '/tournaments/faqs'
    | '/venues/$venueId'
    | '/account'
    | '/admin'
    | '/juniors'
    | '/td'
    | '/tournaments'
    | '/account/registrations/checkout'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/juniors/leaderboard/{-$gender}'
    | '/profile/$profileId/edit'
    | '/tournaments/$tournamentId/edit'
    | '/account/registrations'
    | '/account/verify'
    | '/profile/$profileId'
    | '/tournaments/$tournamentId'
    | '/api/tasks/cleanup/storage'
    | '/tournaments/$tournamentId/$divisionId/{-$tab}'
    | '/matches/playoff/$matchId'
    | '/matches/pool/$matchId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/log-in'
    | '/log-out'
    | '/not-found'
    | '/ratings'
    | '/sanctioning'
    | '/search'
    | '/sign-up'
    | '/account/change-password'
    | '/account/forgot-password'
    | '/account/reset-password'
    | '/account/setup'
    | '/admin/invoices'
    | '/admin/schedule'
    | '/admin/users'
    | '/api/ping'
    | '/faqs/{-$subject}'
    | '/info/cedars'
    | '/juniors/cal-cup'
    | '/leaderboard/{-$gender}'
    | '/tournaments/create'
    | '/tournaments/faqs'
    | '/venues/$venueId'
    | '/account/'
    | '/admin/'
    | '/juniors/'
    | '/td/'
    | '/tournaments/'
    | '/account/registrations/checkout'
    | '/account/verify/success'
    | '/api/auth/$'
    | '/juniors/leaderboard/{-$gender}'
    | '/profile/$profileId/edit'
    | '/tournaments/$tournamentId/edit'
    | '/account/registrations/'
    | '/account/verify/'
    | '/profile/$profileId/'
    | '/tournaments/$tournamentId/'
    | '/api/tasks/cleanup/storage'
    | '/tournaments/$tournamentId/$divisionId/{-$tab}'
    | '/matches/playoff/$matchId/'
    | '/matches/pool/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LogInRoute: typeof LogInRoute
  LogOutRoute: typeof LogOutRoute
  NotFoundRoute: typeof NotFoundRoute
  RatingsRoute: typeof RatingsRoute
  SanctioningRoute: typeof SanctioningRoute
  SearchRoute: typeof SearchRoute
  SignUpRoute: typeof SignUpRoute
  AccountChangePasswordRoute: typeof AccountChangePasswordRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSetupRoute: typeof AccountSetupRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiPingRoute: typeof ApiPingRoute
  FaqsChar123SubjectChar125Route: typeof FaqsChar123SubjectChar125Route
  InfoCedarsRoute: typeof InfoCedarsRoute
  JuniorsCalCupRoute: typeof JuniorsCalCupRoute
  LeaderboardChar123GenderChar125Route: typeof LeaderboardChar123GenderChar125Route
  TournamentsCreateRoute: typeof TournamentsCreateRoute
  TournamentsFaqsRoute: typeof TournamentsFaqsRoute
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JuniorsIndexRoute: typeof JuniorsIndexRoute
  TdIndexRoute: typeof TdIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  AccountRegistrationsCheckoutRoute: typeof AccountRegistrationsCheckoutRoute
  AccountVerifySuccessRoute: typeof AccountVerifySuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  JuniorsLeaderboardChar123GenderChar125Route: typeof JuniorsLeaderboardChar123GenderChar125Route
  ProfileProfileIdEditRoute: typeof ProfileProfileIdEditRoute
  TournamentsTournamentIdEditRoute: typeof TournamentsTournamentIdEditRoute
  AccountRegistrationsIndexRoute: typeof AccountRegistrationsIndexRoute
  AccountVerifyIndexRoute: typeof AccountVerifyIndexRoute
  ProfileProfileIdIndexRoute: typeof ProfileProfileIdIndexRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
  ApiTasksCleanupStorageRoute: typeof ApiTasksCleanupStorageRoute
  TournamentsTournamentIdDivisionIdChar123TabChar125Route: typeof TournamentsTournamentIdDivisionIdChar123TabChar125Route
  MatchesPlayoffMatchIdIndexRoute: typeof MatchesPlayoffMatchIdIndexRoute
  MatchesPoolMatchIdIndexRoute: typeof MatchesPoolMatchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctioning': {
      id: '/sanctioning'
      path: '/sanctioning'
      fullPath: '/sanctioning'
      preLoaderRoute: typeof SanctioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-out': {
      id: '/log-out'
      path: '/log-out'
      fullPath: '/log-out'
      preLoaderRoute: typeof LogOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/td/': {
      id: '/td/'
      path: '/td'
      fullPath: '/td'
      preLoaderRoute: typeof TdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juniors/': {
      id: '/juniors/'
      path: '/juniors'
      fullPath: '/juniors'
      preLoaderRoute: typeof JuniorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId': {
      id: '/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/faqs': {
      id: '/tournaments/faqs'
      path: '/tournaments/faqs'
      fullPath: '/tournaments/faqs'
      preLoaderRoute: typeof TournamentsFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/create': {
      id: '/tournaments/create'
      path: '/tournaments/create'
      fullPath: '/tournaments/create'
      preLoaderRoute: typeof TournamentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/{-$gender}': {
      id: '/leaderboard/{-$gender}'
      path: '/leaderboard/{-$gender}'
      fullPath: '/leaderboard/{-$gender}'
      preLoaderRoute: typeof LeaderboardChar123GenderChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juniors/cal-cup': {
      id: '/juniors/cal-cup'
      path: '/juniors/cal-cup'
      fullPath: '/juniors/cal-cup'
      preLoaderRoute: typeof JuniorsCalCupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/cedars': {
      id: '/info/cedars'
      path: '/info/cedars'
      fullPath: '/info/cedars'
      preLoaderRoute: typeof InfoCedarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/{-$subject}': {
      id: '/faqs/{-$subject}'
      path: '/faqs/{-$subject}'
      fullPath: '/faqs/{-$subject}'
      preLoaderRoute: typeof FaqsChar123SubjectChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/setup': {
      id: '/account/setup'
      path: '/account/setup'
      fullPath: '/account/setup'
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/change-password': {
      id: '/account/change-password'
      path: '/account/change-password'
      fullPath: '/account/change-password'
      preLoaderRoute: typeof AccountChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId/': {
      id: '/profile/$profileId/'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify/': {
      id: '/account/verify/'
      path: '/account/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AccountVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/registrations/': {
      id: '/account/registrations/'
      path: '/account/registrations'
      fullPath: '/account/registrations'
      preLoaderRoute: typeof AccountRegistrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/edit': {
      id: '/tournaments/$tournamentId/edit'
      path: '/tournaments/$tournamentId/edit'
      fullPath: '/tournaments/$tournamentId/edit'
      preLoaderRoute: typeof TournamentsTournamentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId/edit': {
      id: '/profile/$profileId/edit'
      path: '/profile/$profileId/edit'
      fullPath: '/profile/$profileId/edit'
      preLoaderRoute: typeof ProfileProfileIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juniors/leaderboard/{-$gender}': {
      id: '/juniors/leaderboard/{-$gender}'
      path: '/juniors/leaderboard/{-$gender}'
      fullPath: '/juniors/leaderboard/{-$gender}'
      preLoaderRoute: typeof JuniorsLeaderboardChar123GenderChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify/success': {
      id: '/account/verify/success'
      path: '/account/verify/success'
      fullPath: '/account/verify/success'
      preLoaderRoute: typeof AccountVerifySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/registrations/checkout': {
      id: '/account/registrations/checkout'
      path: '/account/registrations/checkout'
      fullPath: '/account/registrations/checkout'
      preLoaderRoute: typeof AccountRegistrationsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/pool/$matchId/': {
      id: '/matches/pool/$matchId/'
      path: '/matches/pool/$matchId'
      fullPath: '/matches/pool/$matchId'
      preLoaderRoute: typeof MatchesPoolMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/playoff/$matchId/': {
      id: '/matches/playoff/$matchId/'
      path: '/matches/playoff/$matchId'
      fullPath: '/matches/playoff/$matchId'
      preLoaderRoute: typeof MatchesPlayoffMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/$divisionId/{-$tab}': {
      id: '/tournaments/$tournamentId/$divisionId/{-$tab}'
      path: '/tournaments/$tournamentId/$divisionId/{-$tab}'
      fullPath: '/tournaments/$tournamentId/$divisionId/{-$tab}'
      preLoaderRoute: typeof TournamentsTournamentIdDivisionIdChar123TabChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/cleanup/storage': {
      id: '/api/tasks/cleanup/storage'
      path: '/api/tasks/cleanup/storage'
      fullPath: '/api/tasks/cleanup/storage'
      preLoaderRoute: typeof ApiTasksCleanupStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LogInRoute: LogInRoute,
  LogOutRoute: LogOutRoute,
  NotFoundRoute: NotFoundRoute,
  RatingsRoute: RatingsRoute,
  SanctioningRoute: SanctioningRoute,
  SearchRoute: SearchRoute,
  SignUpRoute: SignUpRoute,
  AccountChangePasswordRoute: AccountChangePasswordRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSetupRoute: AccountSetupRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiPingRoute: ApiPingRoute,
  FaqsChar123SubjectChar125Route: FaqsChar123SubjectChar125Route,
  InfoCedarsRoute: InfoCedarsRoute,
  JuniorsCalCupRoute: JuniorsCalCupRoute,
  LeaderboardChar123GenderChar125Route: LeaderboardChar123GenderChar125Route,
  TournamentsCreateRoute: TournamentsCreateRoute,
  TournamentsFaqsRoute: TournamentsFaqsRoute,
  VenuesVenueIdRoute: VenuesVenueIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  JuniorsIndexRoute: JuniorsIndexRoute,
  TdIndexRoute: TdIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  AccountRegistrationsCheckoutRoute: AccountRegistrationsCheckoutRoute,
  AccountVerifySuccessRoute: AccountVerifySuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  JuniorsLeaderboardChar123GenderChar125Route:
    JuniorsLeaderboardChar123GenderChar125Route,
  ProfileProfileIdEditRoute: ProfileProfileIdEditRoute,
  TournamentsTournamentIdEditRoute: TournamentsTournamentIdEditRoute,
  AccountRegistrationsIndexRoute: AccountRegistrationsIndexRoute,
  AccountVerifyIndexRoute: AccountVerifyIndexRoute,
  ProfileProfileIdIndexRoute: ProfileProfileIdIndexRoute,
  TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
  ApiTasksCleanupStorageRoute: ApiTasksCleanupStorageRoute,
  TournamentsTournamentIdDivisionIdChar123TabChar125Route:
    TournamentsTournamentIdDivisionIdChar123TabChar125Route,
  MatchesPlayoffMatchIdIndexRoute: MatchesPlayoffMatchIdIndexRoute,
  MatchesPoolMatchIdIndexRoute: MatchesPoolMatchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
